name: Auto Clip Generator

on: 
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Enlace del vídeo de YouTube o Twitch'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
          echo "Recibido el enlace: ${{ github.event.inputs.video_url }}"
          echo "GitHub Actions está listo, pero necesitamos configurar el script de recorte interno."
